#!/bin/bash
#set -x

tablet(){
    xrandr --output eDP-1  --rotate inverted
    xinput set-prop 'Logitech USB Optical Mouse' "Coordinate Transformation Matrix"  -1 0 1 0 -1 1 0 0 1
    xinput set-prop 'Wacom Pen and multitouch sensor Finger touch' "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
    xinput set-prop 'Wacom Pen and multitouch sensor Pen stylus' "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
    xinput set-prop 'SynPS/2 Synaptics TouchPad' "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1

 


}
laptop(){
    xrandr --output eDP-1  --rotate normal
    xinput set-prop 'Logitech USB Optical Mouse' "Coordinate Transformation Matrix"  1 0 1 0 1 1 0 0 1
    xinput set-prop 'Wacom Pen and multitouch sensor Finger touch' "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    xinput set-prop 'Wacom Pen and multitouch sensor Pen stylus' "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    xinput set-prop 'SynPS/2 Synaptics TouchPad' "Coordinate Transformation Matrix" 1 0 1 0 1 1 0 0 1
}

case "$1" in
'tablet')
  tablet
  ;;
'laptop')
  laptop
  ;;
*)
    laptop #be on the safe side...
    echo "usage setmode (laptop|tablet)"
esac







